export const FETCH_BUS_STATION = 'FETCH_BUS_STATION';
export const FETCH_BUS_ALL_STATION = 'FETCH_BUS_ALL_STATION';
export const DETECTED_NEARBY_STATIONS = 'DETECTED_NEARBY_STATIONS';
export const ALL_STATIONS = 'ALL_STATIONS';